Complete the refactor to pymarc
* Second XMLWriter also needs bytes.
* When discarding a subfield, discard its content too. Avoids fake subfield
  names with null content. Symptom of the nonsense subfields wasi IndexError:

  File "/home/federico/.local/lib/python3.7/site-packages/pymarc/writer.py", line 204, in write
    node = pymarc.record_to_xml_node(record)
  File "/home/federico/.local/lib/python3.7/site-packages/pymarc/marcxml.py", line 186, in record_to_xml_node
    for subfield in field:
  File "/home/federico/.local/lib/python3.7/site-packages/pymarc/field.py", line 139, in __next__
    subfield = (self.subfields[self.__pos], self.subfields[self.__pos + 1])
IndexError: list index out of range